---
title: Corona ARD Brennpunkte
author: ''
date: '2022-04-15'
slug: []
categories: []
tags: []
output:
  html_document:
    css: ["custom.css"]
---
```{r init, message=F, echo=F}
library(knitr)
knitr::opts_chunk$set(echo = FALSE,  message = F)
```

```{r package}
library(tidyverse)
library(gt)
library(here)
```

```{r dataload}
path = here("static", "data", "graphs","ardbrennpunkte", "data_corona.csv")
data = readr::read_csv(path)
```

```{r formatdata}
data %>% 
  rename(
    "Datum" = 1,
     "Thema" = 2,
    "Dauer" = 3,
    "Sprecher:In" = 4,
    "Sender" = 5,
    "Zuschauer:Innen" = 6,
    "Quote" = 7
  ) %>% 
  select(-c(Quellen)) %>% 
  mutate(
    Quote = sub("^(\\d{1,2},\\d{1}).*", "\\1", Quote),
    Quote = str_replace(Quote, ",", "\\.") %>% as.numeric()
  ) -> data
```

<style>
.reactable{
  font-family: mono;
}
</style>

```{r gt}
library(reactable)
library(htmltools)

bar_style <- function(width = 1, fill = "#e6e6e6", height = "75%", align = c("left", "right"), color = NULL) {
  align <- match.arg(align)
  if (align == "left") {
    position <- paste0(width * 100, "%")
    image <- sprintf("linear-gradient(90deg, %1$s %2$s, transparent %2$s)", fill, position)
  } else {
    position <- paste0(100 - width * 100, "%")
    image <- sprintf("linear-gradient(90deg, transparent %1$s, %2$s %1$s)", position, fill)
  }
  list(
    backgroundImage = image,
    backgroundSize = paste("100%", height),
    backgroundRepeat = "no-repeat",
    backgroundPosition = "center",
    color = color
  )
}

data %>% reactable::reactable(.,
                              columns = list(Quote = colDef(
                                style = function(value) {
                                  bar_style(width = value / max(data$Quote),
                                            fill = "#2c5e77",
                                            color = "#fff")
                                },
                                align = "left",
                                format = colFormat(digits = 1)
                              )))
```

